import type { ThemeTokens } from "../types";

export const neonDark: ThemeTokens = {
  name: "Neon Dark",
  background: "#0a0a0a",
  foreground: "#ebebeb",
  card: "#0f0f0f",
  cardForeground: "#ebebeb",
  popover: "#0f0f0f",
  popoverForeground: "#ebebeb",
  primary: "#00f0ff",
  primaryForeground: "#0a0a0a",
  secondary: "#1a1a1a",
  secondaryForeground: "#ebebeb",
  muted: "#141414",
  mutedForeground: "#888888",
  accent: "#1a1a1a",
  accentForeground: "#ebebeb",
  destructive: "#ff3860",
  destructiveForeground: "#ffffff",
  border: "#222222",
  input: "#222222",
  ring: "#00f0ff",
  neonCyan: "#00f0ff",
  neonGreen: "#00ff88",
  neonAmber: "#ffb000",
  neonRed: "#ff3860",
  neonPurple: "#bd93f9",
};
